@echo off
chcp 65001 >nul
echo Starting MCP Server...
start "MCP" cmd /k "cd /d e:\008其他\桌面\WEB\project-Life\mcp_server & python main.py"
echo Starting A2A Server...
start "A2A" cmd /k "cd /d e:\008其他\桌面\WEB\project-Life\a2a_server & python main.py"
echo Starting LangGraph Advanced...
start "LangGraph" cmd /k "cd /d e:\008其他\桌面\WEB\project-Life\langgraph_advanced & python main.py"
echo Starting Frontend...
start "Frontend" cmd /k "cd /d e:\008其他\桌面\WEB\project-Life\frontend-agui & npm run dev"
echo All services started!
pause
